### ISSUE TITLE
社交帐号的按钮无法正常显示

### ISSUE THREAD

**Issue by hydroakri** [Huxpro/huxblog-boilerplate#15]
[hssyuan.github.io](url)
最下方的按钮在本地调试的时候正常显示，但是push到github上之后只剩下一个大大的“知”
求解答

**Comment by kaishuibaicai** [comment]
同样的情况，请问楼上问题解决了吗？

**Comment by hydroakri** [comment]
放弃了，用其他模版了

**Comment by kaishuibaicai** [comment]
我的已经不会有这个问题了，但是怎么解决的我也不知道。。。  ksbc24.cn

**Comment by Lanzhou-J** [comment]
相关问题：有text的链接可以显示但图像图标无法正常显示（比如只有知乎可以显示，因为知乎链接是文字“知”）
原因：font-awesome链接不可用
**解决方法：**
将相关文件里（`head.html`）的：
```<link href="http://cdn.staticfile.org/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">```
全部更换为：
```<link href="https://cdn.staticfile.org/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">```
