### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by nephen** [Huxpro/huxblog-boilerplate#4]
When I open the website http://127.0.0.1:4000/tags/, It shows as below, which I think It's not normal.
![hux](https://cloud.githubusercontent.com/assets/7166946/14059308/1b2bf516-f378-11e5-832e-d07edcdff0d6.png)

**Comment by Huxpro** [comment]
@nephen 

Pull the latest commits. I should have fixed it. 

BTW, this issue occurs in local env only

**Comment by nephen** [comment]
@Huxpro Yes, It's the lastest commits.

**Comment by Huxpro** [comment]
@nephen  checkout if you have this commit https://github.com/Huxpro/huxblog-boilerplate/commit/ab20183e9a84b743fd417fda0ae4fe0af5d02132#diff-83246637a92a87da8ffc476ae1ef183bL26 in `tags.html`

**Comment by nephen** [comment]
Get it, ths! @Huxpro
